name: Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate snake animation
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: Sam06002
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_directory: output
          output_filename: github-contribution-grid-snake.svg
